### ISSUE TITLE
hexo g 报错

### ISSUE THREAD

**Issue by Songziyuan** [gzdaijie/koa-react-server-render-blog#70]
有两个问题：
1，一定要配置gittalk，否在就会报错
2，layout里有个报错，还不知道怎么解决，报错信息如下：
ReferenceError: /home/admin/Documents/markdown/hexo/themes/geektutu/layout/page.ejs:83
    81|     
    82|     <div class="col-lg-8 col-md-8 col-sm-12 col-xs-12">
 >> 83|         <%- body %>
    84|     </div>
    85|     <aside id="sidebar" class="hidden-xs hidden-sm">
    86|         <div class="sidebar-wrapper col-xs-12">

body is not defined
    at eval (eval at compile (/home/admin/Documents/markdown/hexo/node_modules/ejs/lib/ejs.js:633:12), <anonymous>:11:17)
    at returnedFn (/home/admin/Documents/markdown/hexo/node_modules/ejs/lib/ejs.js:668:17)
    at Theme._View.View._compiled (/home/admin/Documents/markdown/hexo/node_modules/hexo/lib/theme/view.js:123:48)
    at Theme._View.View.View.render (/home/admin/Documents/markdown/hexo/node_modules/hexo/lib/theme/view.js:29:15)
    at /home/admin/Documents/markdown/hexo/node_modules/hexo/lib/hexo/index.js:349:21
    at tryCatcher (/home/admin/Documents/markdown/hexo/node_modules/bluebird/js/release/util.js:16:23)
    at /home/admin/Documents/markdown/hexo/node_modules/bluebird/js/release/method.js:15:34
    at RouteStream._read (/home/admin/Documents/markdown/hexo/node_modules/hexo/lib/hexo/router.js:123:3)
    at RouteStream.Readable.read (_stream_readable.js:474:10)
    at resume_ (_stream_readable.js:953:12)
    at processTicksAndRejections (internal/process/task_queues.js:77:11)

**Comment by Songziyuan** [comment]
对整个主题只进行了 git clone

**Comment by geektutu** [comment]
@Songziyuan 

Gitalk的问题解决了，现在可以不配置了。

第二个问题，可能是缺少了一些文件，这个仓库 [geektutu-blog](https://github.com/geektutu/geektutu-blog)是我的博客真实在使用的，你可以参考下配置以及，source目录下的文件有什么不一样的地方。

**Comment by Songziyuan** [comment]
很感谢你的及时解惑，但是还是没能解决掉，之前可能贴的报错堆栈信息无法有效获取信息，我贴张截图上来，烦请在有时间的时候看下：
![image](https://user-images.githubusercontent.com/15028748/60769049-ff2fbf00-a0fd-11e9-98b5-88c05f02b28d.png)

**Comment by dataabc** [comment]
遇到了相同的问题，通过修改一些文件解决了。说下方法：
在hexo 主文件夹下有一个source文件夹，里面可能包含_posts、tags等等，每个人的配置不同，文件夹数量和名称就不同。可以保留_posts、tags、series，其它的文件夹删除即可，然后可以把你的about.md、link.md文件放到_posts，它们分别对应"友链"和"留言"，如果没有这些文件你也可以手动创建
通过以上方法解决问题

**Comment by Songziyuan** [comment]
> 遇到了相同的问题，通过修改一些文件解决了。说下方法：
> 在hexo 主文件夹下有一个source文件夹，里面可能包含_posts、tags等等，每个人的配置不同，文件夹数量和名称就不同。可以保留_posts、tags、series，其它的文件夹删除即可，然后可以把你的about.md、link.md文件放到_posts，它们分别对应"友链"和"留言"，如果没有这些文件你也可以手动创建
> 通过以上方法解决问题

找到原因了，我的目录下添加了一个“404.html”的文件，是用于添加腾讯的公益寻人的，多了这个文件，就一直报这个错。
我觉得这个是个可以修复的bug。希望作者能够有时间解决下。
